### ISSUE TITLE
Tutorial: suggested improvements

### ISSUE THREAD

**Issue by lheagy** [achennu/microbenthos#4]
I have worked through the [tutorials in the docs]( 
https://microbenthos.readthedocs.io/en/latest/tutorials/tut01_define/tutorial.html) as a part of the JOSS Review in openjournals/joss-reviews#674. The text is clear, informative and well-linked to additional information and the API. Congrats! 

I just have a couple minor suggestions:
- [x] it would be helpful to have a link to a .yaml file containing the full set of simulation parameters at the top of the file so that users can download scroll through it as they read your tutorial (this also reduces the likely hood of messing up indentations that can easily occur when copy-pasting from a web-page to a local yaml file, particularly if they don't see that a download is available later on in the docs).
- [x] this is minor, but worth addressing: I ran the example on my 13" laptop, and the figure that popped up was larger than the screen (in height), so it might be worth adjusting to also be suitable for smaller screens

**Comment by achennu** [comment]
@lheagy Thanks for the feedback.

I will move the download links to the definition file to the top of each tutorial. You are right, it would make it more useful for the reader.

As for the size of the graphical exporter, the default is currently set to (1200, 800). I had earlier made it smaller, but I found it hard to read. Instead of trying to guess what other monitors look like, I have exposed the figure size as a user changeable option:

```
microbenthos export video --figsize 8x6 --dpi 100
```
will produce a 800x600 graphical output. 

I will dig into whether the ``simulate`` command exposes this option correctly through the ``--exporter`` flag. On second thought, I will look again into making the default smaller.

**Comment by achennu** [comment]
@lheagy I've now updated the tutorials to contain a download link to the definition at the top. Good idea.

I have also changed the default size of the plotter to (800, 600). This should be small enough for most screens, and anyhow the window can be maximized without trouble.

**Comment by lheagy** [comment]
@achennu: it looks like the docs haven't updated yet? or I missed the link?

![image](https://user-images.githubusercontent.com/6361812/39167069-f83803c2-4741-11e8-8559-628ddd52b9a0.png)

**Comment by achennu** [comment]
The docs haven't updated yet. It is an upstream issue with readthedocs https://github.com/rtfd/readthedocs.org/issues/3998

But you can can see the last commit on develop to see the change.

**Comment by achennu** [comment]
@lheagy The problem with readthedocs seems to be fixed.
The updated version can be seen at: http://microbenthos.readthedocs.io/en/develop/tutorials/tut01_define/tutorial.html

**Comment by lheagy** [comment]
This looks great @achennu!
